### ISSUE TITLE
Adjust sample sheet parsing

### ISSUE THREAD

**Issue by alexg9010** [BIMSBbioinfo/pigx_bsseq#105]
We should change the way how the sample sheet is parsed /accessed (here https://github.com/BIMSBbioinfo/pigx_bsseq/blob/master/pigx-bsseq.in#L142-L184) to  the way how the rna-seq did (here https://github.com/BIMSBbioinfo/pigx_bsseq/blob/master/pigx-bsseq.in#L142-L184) and adapt to their more generic approaches (see https://github.com/BIMSBbioinfo/pigx_rnaseq/blob/master/pigx_rnaseq.py#L222-L242). 

Another reason why we should to this, is to make the driver script more independent of each pipeline (except for the help string), which makes Rekado's life at least a bit easier.

**Comment by rekado** [comment]
I agree.  One thing we should consider, though, is to use https://docs.python.org/3/library/csv.html#csv.DictReader instead of trying to implement this ourselves.  This might simplify things even further.

**Comment by Blosberg** [comment]
I'm making this post a sub-topic of this issue (since it seems related) and upgrading its priority to "bug", since the pipeline crashes when there's an empty line. (as described below).

That should make this the highest priority issue.

---------------------------

currently, if the sample sheet is prepared like this (notice the trailing newline):

SRX317877_WT.fq.gz,,WT,WGBS,0
SRX317883_tet2.fq.gz,,tet2,WGBS,1
SRR1578163_WT-day3.fastq.gz,,WTday3,WGBS,2
SRR1578165_tet2-day3.fastq.gz,,tet2day3,WGBS,3

The output will look like this:

$ ./pigx-bsseq samplesheet_usecase.csv -s  settings_usecase.yaml -n
Traceback (most recent call last):
  File "./pigx-bsseq", line 400, in <module>
    args.settings)
  File "./pigx-bsseq", line 241, in generate_config
    sample_params = parse_samples(lines)
  File "./pigx-bsseq", line 163, in parse_samples
    sample_ids = [x[2] for x in rows]
  File "./pigx-bsseq", line 163, in <listcomp>
    sample_ids = [x[2] for x in rows]
IndexError: list index out of range

which is not a clear way of saying "you've got an empty line at the end of your sample sheet". I just wasted about 20 minutes trying to figure out what the problem is --a novice user could easily make the same mistake and just give up on the whole package.

There needs to be either a clear  error message in this case saying "remove the empty line in your sample sheet", or the line needs to be stripped away. Whatever can be accomplished fastest.

**Comment by Blosberg** [comment]
@alexg9010 , I'm currently working on the BSseq main file, but that shouldn't interfere with development of the driver script to handle this issue; can you look into this please?

**Comment by Blosberg** [comment]
@alexg9010 , this patch here: https://github.com/BIMSBbioinfo/pigx_bsseq/commit/eadf7529ebb3ef4b56b424c62a8a06e3d7ed8f95 resolves the error in the specific case of an empty line, which is better. Still though, it would be nice to have more robust case-handling so that any input line that isn't a valid input (i.e., doesn't have the right number of columns) is met with an informative and descriptive error. 

Since we're working against the clock at the moment, though, this item has to be given lower priority to more urgent issues, so I'm wishlist-ing this for now.

**Comment by alexg9010** [comment]
The RNAseq people have more robust case handling, see here: https://github.com/BIMSBbioinfo/pigx_rnaseq/blob/6d64b3ef58f175088f60295fbc58cadd28d0b75a/scripts/validate_input.py
But as you said this can be done later.
