### ISSUE TITLE
Cluster execution fails: file not found

### ISSUE THREAD

**Issue by rekado** [BIMSBbioinfo/pigx_bsseq#53]
When running pigx-bsseq on the cluster with the test data it fails like this: 

```
Traceback (most recent call last):
  File "/gnu/store/jijw1m3gqz9rw7j5ykxa8aqq7w35x8sn-snakemake-4.2.0/lib/python3.5/site-packages/snakemake/io.py", line 321, in touch_or_create
    self.touch()
  File "/gnu/store/jijw1m3gqz9rw7j5ykxa8aqq7w35x8sn-snakemake-4.2.0/lib/python3.5/site-packages/snakemake/io.py", line 315, in touch
    snakefile=self.rule.snakefile)
snakemake.exceptions.MissingOutputException: Output file /home/bosberg/projects/pigx_bsseq_testing/test_basic/test/out/Final_Report/SEsample_v2copy_se_bt2.deduped_hg19_integrateDiffMeth2FinalReport.txt of rule integrateFinalReport shall be touched but does not exist.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/gnu/store/dcjz87kc9md7fppk63vg7g26j39jpfnx-python-3.5.3/lib/python3.5/threading.py", line 914, in _bootstrap_inner
    self.run()
  File "/gnu/store/dcjz87kc9md7fppk63vg7g26j39jpfnx-python-3.5.3/lib/python3.5/threading.py", line 862, in run
    self._target(*self._args, **self._kwargs)
  File "/gnu/store/jijw1m3gqz9rw7j5ykxa8aqq7w35x8sn-snakemake-4.2.0/lib/python3.5/site-packages/snakemake/executors.py", line 759, in _wait_for_jobs
    active_job.callback(active_job.job)
  File "/gnu/store/jijw1m3gqz9rw7j5ykxa8aqq7w35x8sn-snakemake-4.2.0/lib/python3.5/site-packages/snakemake/scheduler.py", line 317, in _proceed
    self.get_executor(job).handle_job_success(job)
  File "/gnu/store/jijw1m3gqz9rw7j5ykxa8aqq7w35x8sn-snakemake-4.2.0/lib/python3.5/site-packages/snakemake/executors.py", line 583, in handle_job_success
    super().handle_job_success(job, upload_remote=False)
  File "/gnu/store/jijw1m3gqz9rw7j5ykxa8aqq7w35x8sn-snakemake-4.2.0/lib/python3.5/site-packages/snakemake/executors.py", line 182, in handle_job_success
    self.dag.handle_touch(job)
  File "/gnu/store/jijw1m3gqz9rw7j5ykxa8aqq7w35x8sn-snakemake-4.2.0/lib/python3.5/site-packages/snakemake/dag.py", line 419, in handle_touch
    f.touch_or_create()
  File "/gnu/store/jijw1m3gqz9rw7j5ykxa8aqq7w35x8sn-snakemake-4.2.0/lib/python3.5/site-packages/snakemake/io.py", line 324, in touch_or_create
    with open(self.file, "w") as f:
FileNotFoundError: [Errno 2] No such file or directory: '/home/bosberg/projects/pigx_bsseq_testing/test_basic/test/out/Final_Report/SEsample_v2copy_se_bt2.deduped_hg19_integrateDiffMeth2FinalReport.txt'
```

There are two possibilities (1) an input is needed here to prevent this rule from executing prematurely, or (2) the processes are not able to access file that they need when running in parallel.

**Comment by rekado** [comment]
Every report generation should produce its very own knitr_meta.rds file; all of these files are then merged at the end.

The `integrateFinalReport` rule is violating snakemake assumptions because it doesn't declare its actual output. The output is a new knitr_meta.rds file, not an empty text file.  Generating an empty text file is a kludge to enforce rule order.
