### ISSUE TITLE
Log file error: "shall be touched but does not exist"

### ISSUE THREAD

**Issue by Blosberg** [BIMSBbioinfo/pigx_bsseq#68]
Only affects runs submitted to the cluster: due to file latency, log files (which are being treated as "outputs") need to be created within a rule, before then being modified. Since they don't exist quickly enough this error is triggered, and the pipeline crashes at rule 1. Run it immediately again and it will crash on rule 2, then 3, etc.

We've already set 'latency-wait' to a large value, but that only catches `output` files; this limitation is really a bug in snakemake and we should report it to the snakemake maintainers, but for the moment, we need to engineer our own workaround. Output pasted below.

```
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/gnu/store/jijw1m3gqz9rw7j5ykxa8aqq7w35x8sn-snakemake-4.2.0/lib/python3.5/site-packages/snakemake/io.py", line 308, in touch
    lutime(self.file, times)
  File "/gnu/store/jijw1m3gqz9rw7j5ykxa8aqq7w35x8sn-snakemake-4.2.0/lib/python3.5/site-packages/snakemake/io.py", line 38, in lutime
    os.utime(f, times, follow_symlinks=False)
FileNotFoundError: [Errno 2] No such file or directory

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/gnu/store/jijw1m3gqz9rw7j5ykxa8aqq7w35x8sn-snakemake-4.2.0/lib/python3.5/site-packages/snakemake/io.py", line 321, in touch_or_create
    self.touch()
  File "/gnu/store/jijw1m3gqz9rw7j5ykxa8aqq7w35x8sn-snakemake-4.2.0/lib/python3.5/site-packages/snakemake/io.py", line 315, in touch
    snakefile=self.rule.snakefile)
snakemake.exceptions.MissingOutputException: Output file 01_raw_QC/SEsample_v2_fastqc.log of rule fastqc_raw shall be touched but does not exist.

During handling of the above exception, another exception occurred:
```

**Comment by rekado** [comment]
It's very ugly, but a workaround would be to touch all log files in advance.

**Comment by rekado** [comment]
We were using snakemake 4.2.0, which didn't create directories before trying to create a file.  This behaviour has changed in 4.4.0, where it would first create a directory and then try to create the file.

**Comment by Blosberg** [comment]
tentatively "fixed" with new version of snakemake
